# Generated by Django 5.1.7 on 2025-03-21 19:04

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccessTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('validator', 'Validator')], max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='pam_user_groups', related_query_name='pam_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='pam_user_permissions', related_query_name='pam_user', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('requested_window', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('window_start', models.DateTimeField()),
                ('is_withdraw', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iam_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pam.accountaccesstypes')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='password_requests', to=settings.AUTH_USER_MODEL)),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='pam_passwor_status_481616_idx'), models.Index(fields=['iam_account'], name='pam_passwor_iam_acc_bc9488_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('requested_window__range', (1, 4))), name='valid_request_window')],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_account_number', models.CharField(max_length=12, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('stage', 'Staging'), ('prod', 'Production')], max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('last_used', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pam.accountaccesstypes')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pam.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'aws_account_number', 'username'], name='pam_account_tenant__80d449_idx')],
                'unique_together': {('tenant', 'aws_account_number', 'username')},
            },
        ),
    ]
