# Generated by Django 5.1.7 on 2025-03-20 21:53

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aws_account_id', models.CharField(max_length=12, unique=True)),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('stage', 'Staging'), ('prod', 'Production')], max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('validator', 'Validator')], max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='pam_user_groups', related_query_name='pam_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='pam_user_permissions', related_query_name='pam_user', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IAMAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('access_level', models.CharField(choices=[('read', 'Read'), ('admin', 'Admin')], max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('expiry_date', models.DateTimeField()),
                ('last_rotated', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pam.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UserTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pam.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('requested_window', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('window_start', models.DateTimeField()),
                ('is_withdraw', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iam_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pam.iamaccount')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='password_requests', to=settings.AUTH_USER_MODEL)),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='pam_passwor_status_481616_idx'), models.Index(fields=['iam_account'], name='pam_passwor_iam_acc_bc9488_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('requested_window__range', (1, 4))), name='valid_request_window')],
            },
        ),
        migrations.AddIndex(
            model_name='iamaccount',
            index=models.Index(fields=['expiry_date'], name='pam_iamacco_expiry__4e844e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='iamaccount',
            unique_together={('tenant', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='usertenant',
            unique_together={('user', 'tenant')},
        ),
    ]
