# Generated by Django 5.1.7 on 2025-03-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
