# Generated by Django 5.1.7 on 2025-03-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0002_tenant_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='observations',
        ),
        migrations.AddField(
            model_name='user',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
