# Generated by Django 4.2.20 on 2025-03-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
