# Generated by Django 5.1 on 2025-04-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0003_remove_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudaccount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='status',
        ),
        migrations.AddField(
            model_name='cloudaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
