# Generated by Django 5.1.7 on 2025-03-22 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0003_remove_tenant_observations_user_observations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='observations',
            new_name='observation',
        ),
    ]
