# Generated by Django 5.1 on 2025-04-07 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0004_remove_cloudaccount_status_remove_tenant_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrequest',
            name='iam_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pam.cloudaccount'),
        ),
        migrations.AlterField(
            model_name='passwordrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active_window', 'Active Window'), ('expired', 'Expired'), ('used', 'Used')], default='pending', max_length=20),
        ),
    ]
