# Generated by Django 5.1.7 on 2025-03-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0004_rename_observations_user_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('validator', 'Validator')], default='user', max_length=20),
        ),
    ]
