# Generated by Django 5.1 on 2025-04-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0005_alter_passwordrequest_iam_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrequest',
            name='justification',
            field=models.TextField(blank=True),
        ),
    ]
