# Generated by Django 5.1.7 on 2025-03-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
