# Generated by Django 5.1.7 on 2025-03-22 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0007_alter_tenant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=12, unique=True)),
                ('provider', models.CharField(choices=[('aws', 'Amazon Web Services')], max_length=20)),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('stage', 'Staging'), ('prod', 'Production')], max_length=20)),
                ('username', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=20)),
                ('last_used', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pam.accountaccesstypes')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pam.tenant')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddIndex(
            model_name='cloudaccount',
            index=models.Index(fields=['tenant', 'account', 'provider', 'username'], name='pam_cloudac_tenant__89c9be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cloudaccount',
            unique_together={('tenant', 'account', 'provider', 'username')},
        ),
    ]
