# Generated by Django 5.1.7 on 2025-03-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0008_cloudaccount_delete_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudaccount',
            name='provider',
            field=models.CharField(choices=[('aws', 'Amazon Web Services'), ('azure', 'Microsoft Azure'), ('gcp', 'Google Cloud Platform'), ('oci', 'Oracle Cloud Infrastructure')], default='aws', max_length=20),
        ),
    ]
