# Generated by Django 5.1.7 on 2025-03-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0011_rename_accountaccesstypes_cloudaccountaccesstypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CloudAccountAccessTypes',
            new_name='CloudAccountAccessType',
        ),
    ]
