# Generated by Django 5.1.7 on 2025-03-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0012_rename_cloudaccountaccesstypes_cloudaccountaccesstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudaccount',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloudaccountaccesstype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
