# Generated by Django 5.1.7 on 2025-03-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0013_alter_cloudaccount_last_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudaccount',
            name='account',
            field=models.CharField(max_length=12),
        ),
    ]
