# Generated by Django 5.1.7 on 2025-03-22 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0014_alter_cloudaccount_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cloudaccount',
            unique_together={('account', 'provider', 'cloud_username')},
        ),
    ]
